stages:
  prepare_data:
    cmd: python src/prepare_data.py
    deps:
    - src/prepare_data.py
    - data/raw
    params:
    - prepare_data
    outs:
    - data/processed
  train:
    cmd: python src/train.py
    deps:
    - src/train.py
    - data/processed
    params:
    - train
    outs:
    - models/model.joblib
    - custom_plots/feat_importance.png
  eval:
    cmd: python src/evaluate.py
    deps:
    - src/evaluate.py
    - data/processed
    - models/model.joblib
    metrics:
    - metrics.json:
        cache: false
plots:
- dvclive/plots/metrics:
    x: step
- dvclive/plots/images
- results/train/plots/metrics:
    x: step
- results/train/plots/images
- results/evaluate/plots/sklearn/confusion_matrix.json:
    template: confusion
    x: actual
    y: predicted
    title: Confusion Matrix
    x_label: True Label
    y_label: Predicted Label
- results/evaluate/plots/sklearn/roc.json:
    template: simple
    x: fpr
    y: tpr
    title: Receiver operating characteristic (ROC)
    x_label: False Positive Rate
    y_label: True Positive Rate
- results/evaluate/plots/sklearn/precision_recall.json:
    template: simple
    x: recall
    y: precision
    title: Precision-Recall Curve
    x_label: Recall
    y_label: Precision
metrics:
- dvclive/metrics.json
- results/train/metrics.json
