stages:
  prepare_data:
    cmd: python src/prepare_data.py
    deps:
    - src/prepare_data.py
    - data/raw
    params:
    - prepare_data
    outs:
    - data/processed
  train:
    cmd: python src/train.py
    deps:
    - src/train.py
    - data/processed
    params:
    - train
    outs:
    - models/model.joblib
    - custom_plots/feat_importance.png
  eval:
    cmd: python src/evaluate.py
    deps:
    - src/evaluate.py
    - data/processed
    - models/model.joblib
    metrics:
    - metrics.json:
        cache: false
plots:
- dvclive/plots/metrics:
    x: step
- dvclive/plots/images
metrics:
- dvclive/metrics.json
