# directories
DATA_DIR = "data"
DATA_RAW_DIR = "data/raw"
DATA_PROCESSED_DIR = "data/processed"
MODELS_DIR = "models"
CUSTOM_PLOTS_DIR = "custom_plots"

# legendary pokemon
SUB_LEGENDARY_LIST = [
    "Articuno",
    "Zapdos",
    "Moltres",
    "Raikou",
    "Entei",
    "Suicune",
    "Regirock",
    "Regice",
    "Registeel",
    "Latias",
    "Latios",
    "Uxie",
    "Mesprit",
    "Azelf",
    "Heatran",
    "Regigigas",
    "Cresselia",
    "Cobalion",
    "Terrakion",
    "Virizion",
    "Tornadus",
    "Thundurus",
    "Landorus",
    "Type: Null",
    "Silvally",
    "Tapu Koko",
    "Tapu Lele",
    "Tapu Bulu",
    "Tapu Fini",
    "Nihilego",
    "Buzzwole",
    "Pheromosa",
    "Xurkitree",
    "Celesteela",
    "Kartana",
    "Guzzlord",
    "Poipole",
    "Naganadel",
    "Stakataka",
    "Blacephalon",
    "Kubfu",
    "Urshifu",
    "Regieleki",
    "Regidrago",
    "Glastrier",
    "Spectrier",
    "Enamorus",
    "Wo-Chien",
    "Chien-Pao",
    "Ting-Lu",
    "Chi-Yu",
    "Okidogi",
    "Munkidori",
    "Fezandipiti",
    "Ogerpon",
]

LEGENDARY_LIST = [
    "Mewtwo",
    "Lugia",
    "Ho-oh",
    "Kyogre",
    "Groudon",
    "Rayquaza",
    "Dialga",
    "Palkia",
    "Giratina",
    "Reshiram",
    "Zekrom",
    "Kyurem",
    "Xerneas",
    "Yveltal",
    "Zygarde",
    "Cosmog",
    "Cosmoem",
    "Solgaleo",
    "Lunala",
    "Necrozma",
    "Zacian",
    "Zamazenta",
    "Eternatus",
    "Calyrex",
    "Koraidon",
    "Miraidon",
]

MYTHICAL_LIST = [
    "Mew",
    "Celebi",
    "Jirachi",
    "Deoxys",
    "Phione",
    "Manaphy",
    "Darkrai",
    "Shaymin",
    "Arceus",
    "Victini",
    "Keldeo",
    "Meloetta",
    "Genesect",
    "Diancie",
    "Hoopa",
    "Volcanion",
    "Magearna",
    "Marshadow",
    "Zeraora",
    "Meltan",
    "Melmetal",
    "Zarude",
]

PARADOX_LIST = ["Walking Wake", "Raging Bolt", "Iron Leaves", "Iron Crown"]

LEGEND_LIST = SUB_LEGENDARY_LIST + LEGENDARY_LIST + MYTHICAL_LIST + PARADOX_LIST
